### ISSUE TITLE
Support binding new objects

### ISSUE THREAD

**Issue by royteeuwen** [bobi/aem-groovyconsole-plugin#156]
We use aem easy content upgrade as framework to do our automated migrations. It would be nice if you could add extra custom bindings (or support aecu) to the AEM Groovy Console Plugin:

For your information, it creates a binding named `aecu` in your groovy scripts, see:
https://github.com/valtech/aem-easy-content-upgrade

**Comment by bobi** [comment]
better to put, "gdsl" file inside some jar file in "aem-easy-content-upgrade" project and groovy editor will take definitions from that file automactically from maven dependencies.

for example "aecu.gdsl" in resources folder in api bundle

```groovy
def aecuCtx = context(scope: scriptScope())

contributor(aecuCtx) {
    field name: 'aecu', type: 'de.valtech.aecu.api.groovy.console.bindings.AecuBinding'
}
```
<img width="1249" alt="Monosnap aem-easy-content-upgrade – aecu  aecu api  2023-08-19 22-41-55" src="https://github.com/bobi/aem-groovyconsole-plugin/assets/122774/4e11fe56-0017-44db-9e81-2504fbe36a75">

<img width="549" alt="Monosnap aem-groovy-console – pom xml (sub-module) 2023-08-19 22-43-38" src="https://github.com/bobi/aem-groovyconsole-plugin/assets/122774/1bf78a14-60d9-4da4-82e7-0f650711e299">

![Monosnap Microsoft Teams Notification 2023-08-19 22-46-49](https://github.com/bobi/aem-groovyconsole-plugin/assets/122774/0b167088-d061-4d8e-8480-0af03ee1da9b)

**Comment by royteeuwen** [comment]
@bobi thanks for adding the support into the plugin! I was still planning to do the gdsl, just didnt get around to it yet :(,
