### ISSUE TITLE
Support for .groovy file extension

### ISSUE THREAD

**Issue by nhirrle** [bobi/aem-groovyconsole-plugin#52]
Hi

First of all, thanks for your great work, the plugin is pretty cool. 

I tried to setup the following but doesn't seem to work as I cannot see the extra bar with "Run on" 
![image](https://user-images.githubusercontent.com/46745410/188489181-e35a94be-96d2-42f5-b7bc-43ba8e4ad2f5.png)

Do you support file extension .groovy as well? If so, could you maybe give me a hint how to configure?

Thanks,
Nicolas

**Comment by bobi** [comment]
.groovy file extension does not support.
aemconsole extension was introduced to separate regular groovy files and aemconsole groovy files, to handle code completion only for specific file extension, but not for all groovy files.

What is the issue to use aemconsole file extension?

**Comment by nhirrle** [comment]
Thanks @bobi 
The usecase is simple: I do have existing groovyscripts and don't want to rename them if not required but still use the plugin.

**Comment by bobi** [comment]
I'll take a look what can be done

**Comment by bobi** [comment]
i have added ability to mark folder as "AEM Scripts Source Root",  so all groovy files in marked folder will be treated as AEM Scripts
